version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=student
      - MYSQL_HOST=db
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: student
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
